### ISSUE TITLE
Create v2.0.0 Production Upgrade Readiness Assessment Document / Checklist

### ISSUE THREAD

**Issue by LuncBurner** [classic-terra/core#209]
**Problem definition**
In advance of the planned v2.0.0 upgrade on Columbus-5, an upgrade readiness assessment document / and upgrade checklist document will be created.

**Acceptance criteria**
Readiness assessment document created and accepted by the team.

- [x] List all upgrade dependencies which have been completed
- [x] Include key milestone ensuring successful result of Rebel-2 chain-halt upgrade
- [x] Create checklist for production upgrade, including lessons learned from previous chain-halt upgrade.
