### ISSUE TITLE
Tracking issue for Core v2.2.0 release

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [classic-terra/core#311]
- [x] [cosmos - sdk v46](https://github.com/classic-terra/cosmos-sdk/pull/8)
- [x] [cometbft](https://github.com/classic-terra/cometbft/tree/v0.34.29-classic)
- [x] update ibc-go to v6 to match with cosmos - sdk v46
- [x] update current wasmd to use cosmos - sdk v46
- [x] wasmd with FundCommunityPool, and genesis fix
- [x] #309 
- [x] https://github.com/classic-terra/core/pull/272
- [x] https://github.com/classic-terra/core/pull/301
- [x] migration guide (https://github.com/classic-terra/documents/blob/main/migration/core_v220.md)

**Comment by nghuyenthevinh2000** [comment]
@alchemist-ti can you check our wasmd compatible with cosmos - sdk v46, there are some incompatibles: https://github.com/classic-terra/wasmd

currently, I am using this modified version of cosmos - sdk v46: https://github.com/classic-terra/cosmos-sdk/pull/8, feel free to modify it if you see fit.

**Comment by nghuyenthevinh2000** [comment]
@inon-man since we are removing legacy rest on cosmos - sdk, I think that we have to discus about rest endpoints migration else station, and all dependant front - end will break heavily
