### ISSUE TITLE
Create Gov Proposal for 50% of Burn Tax and 50% to treasury burn wallet

### ISSUE THREAD

**Issue by LuncBurner** [classic-terra/core#35]
**Tasks**
- [ ] Determine block height required for this update. (Ed) Should be end of March, prior to release of v2.0.4
- [x] Write first proposal with fixed configuration, submit to Agora for voting (Ed)
- [x] Confirm if antehandler fix will be in v1.0.5, based on result of governance vote. (Steve)
- [ ] Communicate required update to validators (Ed)
- [ ] Create proposal repository in github, with workflow (Ed)

**Acceptance Criteria**
- Proposal has been passed or rejected.

**Comment by vuong177** [comment]
We need  https://github.com/classic-terra/classic/pull/27 complete first.

**Comment by LuncBurner** [comment]
[] Determine block height required for this update. (Ed)  Should be end of March, prior to release of v2.0.4
[] Write first proposal with fixed configuration, submit to Agora for voting (Ed) 
[] Confirm if antehandler fix will be in v1.0.5, based on result of governance vote. (Steve)
[] Communicate required update to validators (Ed)
[] Create proposal repository in github, with workflow (Ed)

**Acceptance Criteria**

- Proposal has been passed or rejected.

**Comment by ZaradarBH** [comment]
https://github.com/classic-terra/documents/blob/main/proposals/antehandler-burntax-split-01022023.md

**Comment by StrathCole** [comment]
Shouldn't it be explicitely (more clearly) stated that this will reduce tax burns by 50% and send 50% to CP? As this was removed by the seigniorage proposals lately, it might confuse people.
